version = 1

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "requirements.txt",
]
test_patterns = [
  "test_*.py"
]

  [analyzers.meta]
  runtime_version = "3.x.x"